
install:
  - ps: Invoke-WebRequest https://cran.r-project.org/bin/windows/base/old/3.6.3/R-3.6.3-win.exe -OutFile R-win.exe
  - ps: Start-Process -FilePath ./R-win.exe -ArgumentList "/VERYSILENT /DIR=C:\R" -NoNewWindow -Wait
  - ps: $env:PATH += ";C:\R\bin\x64"
  - cinst pandoc
  - ps: $env:PATH += ";C:\Program Files\Pandoc"

build_script:
  - Rscript build.R
  - '7z a -tzip all.zip *.html *.sav *.Rmd *.svg *.png *.zip *.css'

artifacts:
  - path: '*.html'
    name: content
  - path: '*.sav'
    name: data
  - path: '*.Rmd'
    name: Rmarkdown
  - path: '*.svg'
    name: svg files
  - path: '*.png'
    name: png files
  - path: '*.zip'
    name: zip files
  - path: '*.jpg'
    name: jpg files
  - path: '*.css'
    name: css files
  - path: .\Lecture_01_files\*
    name: test files

deploy:
    provider: S3
    access_key_id:
        secure: HEhOfs5oEuCU4xgi/Wx7fv5UCktGQyG9zoRqYGcObKI=
    secret_access_key:
        secure: Cl+DccBdfvPAQpuzOzHlkbBF6tNqW7/eSOMKlW8r/zyWt3S0eYvL0h/Poar4DbyI
    bucket: uon-stat2000-lectures
    region: us-east-2
    set_public: true
